repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        args: ["--line-length", "99"]
        entry: pipenv run black
        types: [python]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        args: ["--profile", "black"]
        entry: pipenv run isort
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy --follow-imports silent
        types: [python]

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pipenv run pytest
        types: [python]
        pass_filenames: false

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run pytest --cov api --cov-fail-under=70
        types: [python]
        pass_filenames: false