language: python
os: linux
cache: pip
matrix:
  fast_finish: true
  include:
    - python: 3.8.7
      dist: bionic

before_install:
    - pip install -U pip
    - pip install poetry

install:
    - poetry install
    - python -c "from ruts.datasets import SovChLit; scl = SovChLit(); scl.download()"
    - python -c "from ruts.datasets import StalinWorks; sw = StalinWorks(); sw.download()"

script:
    - poetry run pytest --cov api --cov-fail-under 90

after_success:
    - codecov