language: python
os: linux
cache: pip
matrix:
  fast_finish: true
  include:
    - python: 3.8
      dist: bionic

before_install:
    - pip install -U pip
    - pip install poetry

install:
    - poetry install

script:
    - poetry run pytest --cov api --cov-fail-under 80

after_success:
    - codecov