language: python
os: linux
cache: pip
matrix:
  fast_finish: true
  include:
    - python: 3.8
      dist: bionic

install:
    - "pip install pipenv pytest-cov codecov"
    - "pipenv install --dev"

script:
    - "python -m pytest --cov=api --cov-fail-under=70"

after_success:
    - codecov